--- makefile.ORIG 2023-09-01 13:23:28.498081000 +1200
+++ makefile 2023-09-01 13:23:52.160868414 +1200
@@ -224,9 +224,9 @@

 # Linux Intel Fortran Compiler and Intel MPI

-impi_intel_linux : FFLAGS = -m64 -fc=$(I_IFORT) -O2 -ipo -no-wrap-margin $(GITINFO) $(INTELMPI_COMPINFO) $(FFLAGSMKL_INTEL) -DUSE_IFPORT
+impi_intel_linux : FFLAGS = -m64 -O2 -ipo -no-wrap-margin $(GITINFO) $(INTELMPI_COMPINFO) $(FFLAGSMKL_INTEL) -DUSE_IFPORT
 impi_intel_linux : LFLAGSMKL = $(LFLAGSMKL_INTEL)
-impi_intel_linux : FCOMPL = mpiifort
+impi_intel_linux : FCOMPL = ftn
 impi_intel_linux : obj = fds_impi_intel_linux
 impi_intel_linux : setup $(obj_mpi)
  $(FCOMPL) $(FFLAGS) -o $(obj) $(obj_mpi) $(LFLAGSMKL)
