#!/bin/bash

rm program.exe

name="Coupled7_6"
path_to_file=$(echo "$name" | tr 'A-Z' 'a-z')

ifx -mcmodel=medium  -o program.exe  glue_output.f90 -I/usr/local/netcdf-ifort/4.6.1/include -I/usr/local/netcdf-ifort/4.6.1/include -L/usr/local/netcdf-ifort/4.6.1/lib -lnetcdff -shared-intel -L/usr/lib -I/usr/include -lnetcdf -lm


cp program.exe /mnt/data2/data2/FDS/fds_work/test_runs_local/$path_to_file
cd /mnt/data2/data2/FDS/fds_work/test_runs_local/$path_to_file
./program.exe $name
mv OUT_$name.nc /mnt/data2/data2/FDS/fds_work/fds_scripts/



