#!/bin/bash

rm program.exe

#Use 7_6 to make BC for 8_3!
#name="Coupled7_6"
#path_to_file=$(echo "$name" | tr 'A-Z' 'a-z')

#ifx -mcmodel=medium  -o program.exe  make_bc_from_palm.f90 -I/usr/local/netcdf-ifort/4.6.1/include -I/usr/local/netcdf-ifort/4.6.1/include -L/usr/local/netcdf-ifort/4.6.1/lib -lnetcdff -shared-intel -L/usr/lib -I/usr/include -lnetcdf -lm


ifx -mcmodel=medium  -o program.exe  make_bc_from_palm_single.f90 -I/usr/local/netcdf-ifort/4.6.1/include -I/usr/local/netcdf-ifort/4.6.1/include -L/usr/local/netcdf-ifort/4.6.1/lib -lnetcdff -shared-intel -L/usr/lib -I/usr/include -lnetcdf -lm


cp program.exe /mnt/data2/data2/FDS/PALM_data_for_FDS/
cd /mnt/data2/data2/FDS/PALM_data_for_FDS/
./program.exe T
./program.exe U
./program.exe V
./program.exe W

cdo merge bc_palm_c3_*.nc bc_palm_c3.nc

rm program.exe


mv bc_*.nc /mnt/data2/data2/FDS/fds_work/fds_scripts/



