#!/bin/bash

rm program.exe

#Use 7_6 to make BC for 8_3!
!name="Coupled7_6"
!path_to_file=$(echo "$name" | tr 'A-Z' 'a-z')

ifx -mcmodel=medium  -o program.exe  IC_palm_c1.f90 -I/usr/local/netcdf-ifort/4.6.1/include -I/usr/local/netcdf-ifort/4.6.1/include -L/usr/local/netcdf-ifort/4.6.1/lib -lnetcdff -shared-intel -L/usr/lib -I/usr/include -lnetcdf -lm


cp program.exe /mnt/data2/data2/FDS/PALM_data_for_FDS/
cd /mnt/data2/data2/FDS/PALM_data_for_FDS/
./program.exe 
rm program.exe
mv ic_*.nc /mnt/data2/data2/FDS/fds_work/fds_scripts/



